### ISSUE TITLE
Exercises are already completed

### ISSUE THREAD

**Issue by iwasdavid** [jorgef/fsharpworkshop#16]
I might be missing something here, but why are the following files already completed? https://github.com/jorgef/fsharpworkshop/blob/master/Module1/Application/Types.fs

I downloaded this a while ago and I thought the whole point was to complete ourselves..do I need a different branch for un completed projects?

**Comment by iwasdavid** [comment]
I’ve forked it and restored it to a state I believe it should be in for starting the exercises if you want me to create a PR: https://github.com/iwasdavid/fsharpworkshop (unless It’s supposed to be like it is)

**Comment by jorgef** [comment]
@iwasdavid thanks for the heads up. I just reverted the PR that caused this problem. Sorry for the confusion.

**Comment by iwasdavid** [comment]
Thank you
